spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 86400000
  secret: '{cipher}AYCRGPraox2jeF39q0lq3W0g0EV1HilIbGi52Ooec0y7SH/B9eJaBy7cGP1uQJriTIta07bJXgK9555r/LaAWC1l5Ik53zU38469R7+i2ThLGjJRw6Sllvi0vG7F5wONxjYIkc7PI29ZTkjz3C2q42nhZGdLTQqvr9lDUP6/0ijciNrI9csdwGz/MK5ujGedmqGgrkRFaEvEw1bjjKzl2rCbNjxtMLJRnykI6D8W2ATX/qyx16/jncTqnDXZGlHfOcGZk/sN97t+SUuYsih5D4NMzZqSHRHQChi02gT247cGNcqexP45qQH1sqIIsFEpFufHneM9WZukceW8+hv3xYue1j0B3103+UkiLeUAGZIl+/LmDUPnaBHK5foOpjyT/XBF6vJGiM3xrhjIbgGXO781nE6b0JhxT2sweFICzLwAGR6ROyTBoyF/C3bw0KrIjEPhc3H+quAfu4rnCM7CS7AoQRmQh1mtugBUL73vjf2anSFaj2/dJ7gSIQeJRDfdeIfJTog9a9N+Nth7UurOonHCe5Fmn5JlaEOgpZKb8rxaTA=='
gateway:
  ip: 172.20.0.5

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order-is-empty: User's order is empty.



    